name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade tox tox-gh-actions
      - name: Set locale ubuntu
        if: runner.os == 'Linux'
        run: sudo locale-gen fa_IR
      - name: Tox tests
        run: |
          tox -v

  ruff:
    runs-on: ubuntu-latest
    name: ruff
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          architecture: x64
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run ruff check
        run: |
          ruff check
          ruff format --check

  pyright:
    runs-on: ubuntu-latest
    name: pyright
    steps:
      - uses: actions/checkout@v7
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3"  # latest Python 3.x
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyright pytest
          pip install -e .
      - name: Run pyright
        run: pyright